version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
before_build:
- cmd: >-
    cd BaseStation
    $libFile = "libs.zip";
    Invoke-WebRequest "https://students.washington.edu/uwrobots/libraries.zip" -OutFile $libFile
    Expand-Archive -Path $libFile -DestinationPath "libraries"
    nuget restore
build:
  project: BaseStation\BaseStation.sln
  verbosity: minimal
after_build:
- ps: >-
    cd EntryPoint\bin\Debug

    Compress-Archive -Path * -DestinationPath build.zip
artifacts:
- path: BaseStation\EntryPoint\bin\Debug\build.zip
  name: BaseStation Zip
deploy:
- provider: GitHub
  tag: BaseStation-v$(appveyor_build_version)
  auth_token:
    secure: 65hrox5EJa5DUZ2Geddz8Mx0/KTpbWl6EXgag78F0Bou4YgAauaezz3FClTCjsQK
  artifact: BaseStation Zip
only_commits:
  files:
    - BaseStation/
